### ISSUE TITLE
Reconnect function

### ISSUE THREAD

**Issue by Zacktamondo** [LenhartStephan/flutter_blue_classic#3]
Hello, First of all, thanks for the amazing package.
Is it possible to make a reconnect function that I can pass the same connection to it and simply reconnect without the need to make a new connection.

**Comment by LenhartStephan** [comment]
I don't think such a function would be possible, because as soon as you close the connection, Android releases any system resources associated with it. See [Android developer: BluetoothSocket close()](https://developer.android.com/reference/android/bluetooth/BluetoothSocket#close()).
So to re-establish a connection, you would need to create a new connection and call connect with the given MAC-Address again.

**Comment by LenhartStephan** [comment]
If you have other thoughts or suggestions regarding this, please feel free to reopen this issue.
