### ISSUE TITLE
Add Ios Code to Connect flutter_blue_classic 

### ISSUE THREAD

**Issue by udayecozen** [LenhartStephan/flutter_blue_classic#6]
Write now  this package has support in Android , please do code in IOS also

**Comment by LenhartStephan** [comment]
Hey there, 
as mentioned in the Readme, it is not possible to add iOS support, because this package aims solely to provide support for Bluetooth **Classic**. Apple only provides open access to Bluetooth LE. To connect to a Bluetooth Classic device, the device itself must be certified with Apples _[MFi (Made for iPod/iPhone)](https://mfi.apple.com/en/faqs)_ program and the developer must use their [External Accessory Framework](https://developer.apple.com/documentation/externalaccessory/) framework. Since this framwork is vastly different from normal Bluetooth operation, iOS support is not possible.

So if you need Bluetooth support on iOS you have two options: 
1. If your device supports Bluetooth LE, use [flutter_blue_plus](https://pub.dev/packages/flutter_blue_plus). It's an excellent package and very well maintained.
2. If you really, really need Bluetooth Classic support, you will need to implement the External Accessory framework on the platform code of your app yourself.
